Brenda: Grid Class Reference
Grid Class Reference
#include <Grid.h>
Public Member Functions
Grid (int width, int height)
Cell & at (int x, int y)
const Cell & at (int x, int y) const
int getWidth () const
int getHeight () const
void dump () const
Dumps the grid to console in ASCII format Shows obstacles as '#' and movement costs as numbers.
bool loadFromJson (const std::string &filename)
bool loadFromTiled (const std::string &filename)
Load grid from a Tiled Map Editor JSON file.
void cycleTileType (int x, int y)
Cycles a tile to the next type when clicked.
void saveToJson (const std::string &filename)
Save current grid state back to environment.json.
Public Attributes
std::unordered_map< std::string, Zone > zones
A map to store named rectangular zones. The key is the zone name (e.g., "Forest", "Cafe").
Private Attributes
int width
int height
std::vector< Cell > cells
Detailed Description
Definition at line 36 of file Grid.h.
Constructor & Destructor Documentation
Grid()
Grid::Grid (int width, int height) inline
Definition at line 39 of file Grid.h.
        : width(width), height(height), cells(width * height) {}
Member Function Documentation
at() [1/2]
Cell & Grid::at (int x, int y) inline
Definition at line 42 of file Grid.h.
{
        return cells[y * width + x];
    }
References cells, and width.
Referenced by cycleTileType(), dump(), Pathfinder::findPath(), Pathfinder::findPathToZone(), PlayerController::handleEvent(), loadFromJson(), TiledParser::processTileLayer(), GridRenderer::render(), and saveToJson().
at() [2/2]
const Cell & Grid::at (int x, int y) const inline
Definition at line 46 of file Grid.h.
{
        return cells[y * width + x];
    }
References cells, and width.
cycleTileType()
void Grid::cycleTileType (int x, int y) inline
Cycles a tile to the next type when clicked.
Definition at line 194 of file Grid.h.
{
        if (x < 0 || x >= width || y < 0 || y >= height) return;
        Cell& cell = at(x, y);
        // Define the cycle order
        switch (cell.obstacle) {
            case ObstacleType::None:
                cell.obstacle = ObstacleType::Grass;
                cell.cost = 10;
                break;
            case ObstacleType::Grass:
                cell.obstacle = ObstacleType::Path;
                cell.cost = 5;
                break;
            case ObstacleType::Path:
                cell.obstacle = ObstacleType::Forest;
                cell.cost = 20;
                break;
            case ObstacleType::Forest:
                cell.obstacle = ObstacleType::Water;
                cell.cost = 100;
                break;
            case ObstacleType::Water:
                cell.obstacle = ObstacleType::Wall;
                cell.cost = 9999;
                break;
            case ObstacleType::Wall:
                cell.obstacle = ObstacleType::None;
                cell.cost = 1;
                break;
        }
    }
References at(), Cell::cost, Forest, Grass, height, None, Cell::obstacle, Path, Wall, Water, and width.
Referenced by main().
dump()
void Grid::dump () const inline
Dumps the grid to console in ASCII format Shows obstacles as '#' and movement costs as numbers.
Definition at line 57 of file Grid.h.
                      {
        std::cout << "Grid (" << width << "x" << height << "):\n";
        std::cout << "Legend: # = Wall, numbers = movement cost\n\n";
        // Print column numbers header
        std::cout << "   ";
        for (int x = 0; x < width; ++x) {
            std::cout << std::setw(3) << x;
        }
        std::cout << "\n";
        // Print top border
        std::cout << "  +";
        for (int x = 0; x < width; ++x) {
            std::cout << "---";
        }
        std::cout << "+\n";
        // Print each row
        for (int y = 0; y < height; ++y) {
            std::cout << std::setw(2) << y << "|";
            for (int x = 0; x < width; ++x) {
                const Cell& cell = at(x, y); // Use the at() method instead of cells[y][x]
                // if (cell.obstacle == ObstacleType::Wall) {
                //     std::cout << " # ";
                // } else
                {
                    // Show movement cost for non-wall tiles
                    if (cell.cost >= 100) {
                        std::cout << "99+"; // Cap display at 99 for formatting
                    } else {
                        std::cout << std::setw(2) << cell.cost << " ";
                    }
                }
            }
            std::cout << "|\n";
        }
        // Print bottom border
        std::cout << "  +";
        for (int x = 0; x < width; ++x) {
            std::cout << "---";
        }
        std::cout << "+\n\n";
        // Print loaded zones
        if (!zones.empty()) {
            std::cout << "Loaded Zones:\n";
            for (const auto& [name, zone] : zones) {
                std::cout << " - " << std::setw(10) << std::left << name
                          << " (x:" << zone.x << ", y:" << zone.y
                          << ", w:" << zone.width << ", h:" << zone.height << ")\n";
            }
            std::cout << "\n";
        }
    }
References at(), Cell::cost, height, width, and zones.
Referenced by main().
getHeight()
int Grid::getHeight () const inline
Definition at line 51 of file Grid.h.
{ return height; }
References height.
Referenced by Pathfinder::findPath(), PlayerController::handleEvent(), loadFromJson(), TiledParser::processTileLayer(), and GridRenderer::render().
getWidth()
int Grid::getWidth () const inline
Definition at line 50 of file Grid.h.
{ return width; }
References width.
Referenced by Pathfinder::findPath(), PlayerController::handleEvent(), loadFromJson(), TiledParser::processTileLayer(), Pathfinder::reconstructPath(), and GridRenderer::render().
loadFromJson()
bool Grid::loadFromJson (const std::string & filename) inline
Definition at line 115 of file Grid.h.
{
        std::ifstream file(filename);
        if (!file) return false;
        nlohmann::json j;
        try {
            j = nlohmann::json::parse(file, nullptr, true, true);
        } catch (const nlohmann::json::parse_error& e) {
            std::cerr << "Error parsing environment.json: " << e.what() << std::endl;
            return false;
        }
        this->width = j.value("width", 0);
        this->height = j.value("height", 0);
        this->cells.assign(this->width * this->height, Cell{}); // Re-initialize the cells vector
        // 1. Read tile properties (like cost) into a map for quick lookup
        std::unordered_map<std::string, int> tileCosts;
        if (j.contains("tile_properties"))
        {
            for (auto& [type, props] : j["tile_properties"].items())
            {
                tileCosts[type] = props.value("cost", 1);
            }
        }
        // Helper map for string to enum conversion
        std::unordered_map<std::string, ObstacleType> stringToObstacleType = {
            {"Wall", ObstacleType::Wall},
            {"Water", ObstacleType::Water},
            {"Forest", ObstacleType::Forest},
            {"Grass", ObstacleType::Grass},
            {"Path", ObstacleType::Path}
        };
        // 2. Process all tiles to set their type and cost
        if (j.contains("tiles")) {
            for (const auto& tile : j["tiles"]) {
                int x = tile.value("x", -1);
                int y = tile.value("y", -1);
                std::string typeStr = tile.value("type", "None");
                // Use this->at() or just at() - no more "grid."
                if (x >= 0 && x < getWidth() && y >= 0 && y < getHeight())
                {
                    auto it = stringToObstacleType.find(typeStr);
                    at(x, y).obstacle = (it != stringToObstacleType.end()) ? it->second : ObstacleType::None;
                    at(x, y).cost = tileCosts.count(typeStr) ? tileCosts[typeStr] : 1;
                }
            }
        }
        // 3. Process the zones
        if (j.contains("zones")) {
            for (auto& [name, zone_data] : j["zones"].items()) {
                // Use this->zones or just zones
                zones[name] = {
                    zone_data.value("x", 0),
                    zone_data.value("y", 0),
                    zone_data.value("width", 0),
                    zone_data.value("height", 0)
                };
            }
        }
        return true;
    }
References at(), cells, Cell::cost, Forest, getHeight(), getWidth(), Grass, height, None, Cell::obstacle, Path, Wall, Water, width, and zones.
Referenced by main().
loadFromTiled()
bool Grid::loadFromTiled (const std::string & filename)
Load grid from a Tiled Map Editor JSON file.
Parameters
filename Path to the .json file exported from Tiled
Returns
true if successful, false otherwise
Definition at line 4 of file Grid.cpp.
{
    return TiledParser::loadTiledMap(filename, *this);
}
References TiledParser::loadTiledMap().
Referenced by main().
saveToJson()
void Grid::saveToJson (const std::string & filename) inline
Save current grid state back to environment.json.
Definition at line 231 of file Grid.h.
{
        nlohmann::json j;
        // Add width and height
        j["width"] = width;
        j["height"] = height;
        // Add tile_properties (preserve original structure)
        j["tile_properties"] = {
            {"Wall", {{"cost", 9999}}},
            {"Forest", {{"cost", 20}}},
            {"Water", {{"cost", 50}}},
            {"Grass", {{"cost", 10}}},
            {"Path", {{"cost", 5}}},
            {"Plain", {{"cost", 0}}}
        };
        // Convert cells back to tiles array
        nlohmann::json tiles = nlohmann::json::array();
        for (int y = 0; y < height; ++y) {
            for (int x = 0; x < width; ++x) {
                const Cell& cell = at(x, y);
                if (cell.obstacle != ObstacleType::None) {
                    std::string type;
                    switch (cell.obstacle) {
                        case ObstacleType::Wall: type = "Wall"; break;
                        case ObstacleType::Water: type = "Water"; break;
                        case ObstacleType::Forest: type = "Forest"; break;
                        case ObstacleType::Grass: type = "Grass"; break;
                        case ObstacleType::Path: type = "Path"; break;
                        default: continue;
                    }
                    tiles.push_back({{"type", type}, {"x", x}, {"y", y}});
                }
            }
        }
        j["tiles"] = tiles;
        // Add zones (preserve existing zones from original file)
        j["zones"] = {
            {"Cafe", {{"x", 1}, {"y", 1}, {"width", 4}, {"height", 4}}},
            {"Bureau", {{"x", 20}, {"y", 2}, {"width", 4}, {"height", 3}}},
            {"Work", {{"x", 8}, {"y", 7}, {"width", 10}, {"height", 8}}},
            {"Home", {{"x", 25}, {"y", 10}, {"width", 2}, {"height", 2}}},
            {"Home_2", {{"x", 30}, {"y", 10}, {"width", 2}, {"height", 2}}},
            {"Home_3", {{"x", 35}, {"y", 10}, {"width", 2}, {"height", 2}}},
            {"Home_4", {{"x", 25}, {"y", 16}, {"width", 2}, {"height", 2}}},
            {"Home_5", {{"x", 29}, {"y", 15}, {"width", 4}, {"height", 4}}},
            {"Home_6", {{"x", 34}, {"y", 15}, {"width", 4}, {"height", 4}}},
            {"Stadium", {{"x", 15}, {"y", 22}, {"width", 10}, {"height", 6}}},
            {"Forest_0", {{"x", 5}, {"y", 10}, {"width", 3}, {"height", 3}}},
            {"Forest_1", {{"x", 30}, {"y", 5}, {"width", 3}, {"height", 3}}},
            {"Forest_2", {{"x", 5}, {"y", 25}, {"width", 4}, {"height", 4}}},
            {"Forest_3", {{"x", 35}, {"y", 20}, {"width", 5}, {"height", 3}}},
            {"Water_1", {{"x", 15}, {"y", 3}, {"width", 2}, {"height", 2}}},
            {"Water_2", {{"x", 25}, {"y", 5}, {"width", 3}, {"height", 2}}},
            {"Water_3", {{"x", 2}, {"y", 20}, {"width", 9}, {"height", 1}}},
            {"Water_4", {{"x", 28}, {"y", 22}, {"width", 4}, {"height", 4}}}
        };
        std::ofstream file(filename);
        file << j.dump(2); // Pretty print with 2-space indentation
    }
References at(), Forest, Grass, height, None, Cell::obstacle, Path, Wall, Water, and width.
Referenced by main().
Member Data Documentation
cells
std::vector<Cell> Grid::cells private
Definition at line 304 of file Grid.h.
Referenced by at(), at(), and loadFromJson().
height
int Grid::height private
Definition at line 303 of file Grid.h.
Referenced by cycleTileType(), dump(), getHeight(), loadFromJson(), and saveToJson().
width
int Grid::width private
Definition at line 303 of file Grid.h.
Referenced by at(), at(), cycleTileType(), dump(), getWidth(), loadFromJson(), and saveToJson().
zones
std::unordered_map<std::string, Zone> Grid::zones
A map to store named rectangular zones. The key is the zone name (e.g., "Forest", "Cafe").
Definition at line 299 of file Grid.h.
Referenced by dump(), AISystem::executeMovementPlan(), Pathfinder::findPathToZone(), AISystem::getHomeZone(), HomeManager::getNpcHomeCoordinates(), AISystem::getRandomLeisureZone(), loadFromJson(), AISystem::planNextAction(), AISystem::processArrivingEntities(), TiledParser::processObjectGroup(), GridRenderer::render(), and GridRenderer::renderWithLabels().
The documentation for this class was generated from the following files:
/home/sean/Projects/Brenda/src/Grid.h
/home/sean/Projects/Brenda/src/Grid.cpp