Brenda: HomeManager Class Reference
HomeManager Class Reference
#include <HomeManager.h>
Public Member Functions
HomeManager ()
bool assignHome (int npcId, const std::string &npcName)
std::string getNpcHome (int npcId) const
int getHomeResident (const std::string &homeName) const
std::vector< HomeAssignment > getAllAssignments () const
void unassignHome (int npcId)
bool getNpcHomeCoordinates (int npcId, const Grid &grid, int &homeX, int &homeY) const
Private Attributes
std::unordered_map< int, std::string > npcToHome
std::unordered_map< std::string, int > homeToNpc
std::vector< std::string > availableHomes
Detailed Description
Definition at line 14 of file HomeManager.h.
Constructor & Destructor Documentation
HomeManager()
HomeManager::HomeManager () inline
Definition at line 21 of file HomeManager.h.
                  {
        // Initialize with all available home zones
        availableHomes = {
            "Home", "Home_2", "Home_3", "Home_4", "Home_5", "Home_6"
        };
    }
References availableHomes.
Member Function Documentation
assignHome()
bool HomeManager::assignHome (int npcId, const std::string & npcName) inline
Assigns a home to an NPC
Definition at line 31 of file HomeManager.h.
{
        // Check if NPC already has a home
        if (npcToHome.find(npcId) != npcToHome.end()) {
            return true; // Already has a home
        }
        // Find an available home
        for (const auto& homeName : availableHomes) {
            if (homeToNpc.find(homeName) == homeToNpc.end()) {
                // This home is available
                npcToHome[npcId] = homeName;
                homeToNpc[homeName] = npcId;
                std::cout << "Assigned " << npcName << " (ID: " << npcId << ") to " << homeName << std::endl;
                return true;
            }
        }
        std::cout << "Warning: No available homes for " << npcName << " (ID: " << npcId << ")" << std::endl;
        return false; // No available homes
    }
References availableHomes, homeToNpc, and npcToHome.
Referenced by main().
getAllAssignments()
std::vector< HomeAssignment > HomeManager::getAllAssignments () const inline
Gets all home assignments
Definition at line 71 of file HomeManager.h.
{
        std::vector<HomeAssignment> assignments;
        for (const auto& [npcId, homeName] : npcToHome) {
            assignments.push_back({homeName, npcId, "NPC_" + std::to_string(npcId)});
        }
        return assignments;
    }
References npcToHome.
Referenced by main().
getHomeResident()
int HomeManager::getHomeResident (const std::string & homeName) const inline
Gets the NPC ID living in a specific home
Definition at line 63 of file HomeManager.h.
{
        auto it = homeToNpc.find(homeName);
        return (it != homeToNpc.end()) ? it->second : -1;
    }
References homeToNpc.
getNpcHome()
std::string HomeManager::getNpcHome (int npcId) const inline
Gets the home zone name for an NPC
Definition at line 55 of file HomeManager.h.
{
        auto it = npcToHome.find(npcId);
        return (it != npcToHome.end()) ? it->second : "";
    }
References npcToHome.
Referenced by AISystem::getHomeZone(), and getNpcHomeCoordinates().
getNpcHomeCoordinates()
bool HomeManager::getNpcHomeCoordinates (int npcId, const Grid & grid, int & homeX, int & homeY) const inline
Gets the home zone coordinates for an NPC
Definition at line 94 of file HomeManager.h.
{
        std::string homeName = getNpcHome(npcId);
        if (homeName.empty()) return false;
        auto it = grid.zones.find(homeName);
        if (it != grid.zones.end()) {
            const Zone& zone = it->second;
            // Return center of the home zone
            homeX = zone.x + zone.width / 2;
            homeY = zone.y + zone.height / 2;
            return true;
        }
        return false;
    }
References getNpcHome(), Zone::height, Zone::width, Zone::x, Zone::y, and Grid::zones.
unassignHome()
void HomeManager::unassignHome (int npcId) inline
Removes an NPC's home assignment
Definition at line 82 of file HomeManager.h.
{
        auto it = npcToHome.find(npcId);
        if (it != npcToHome.end()) {
            std::string homeName = it->second;
            npcToHome.erase(it);
            homeToNpc.erase(homeName);
        }
    }
References homeToNpc, and npcToHome.
Member Data Documentation
availableHomes
std::vector<std::string> HomeManager::availableHomes private
Definition at line 18 of file HomeManager.h.
Referenced by assignHome(), and HomeManager().
homeToNpc
std::unordered_map<std::string, int> HomeManager::homeToNpc private
Definition at line 17 of file HomeManager.h.
Referenced by assignHome(), getHomeResident(), and unassignHome().
npcToHome
std::unordered_map<int, std::string> HomeManager::npcToHome private
Definition at line 16 of file HomeManager.h.
Referenced by assignHome(), getAllAssignments(), getNpcHome(), and unassignHome().
The documentation for this class was generated from the following file:
/home/sean/Projects/Brenda/src/HomeManager.h