Brenda: PositionManager Class Reference
PositionManager Class Reference
#include <PositionManager.h>
Public Member Functions
PositionComponent * create (unsigned int entityUID, float x, float y)
PositionComponent * get (unsigned int entityUID) const
void dump () override
Pure virtual update function.
Public Member Functions inherited from IComponentManager
virtual ~IComponentManager ()=default
Virtual destructor.
Public Attributes
std::unordered_map< unsigned int, std::unique_ptr< PositionComponent > > positions
Detailed Description
Definition at line 10 of file PositionManager.h.
Member Function Documentation
create()
PositionComponent * PositionManager::create (unsigned int entityUID, float x, float y) inline
Definition at line 14 of file PositionManager.h.
{
        auto position = std::make_unique<PositionComponent>(x, y);
        PositionComponent* ptr = position.get();
        positions[entityUID] = std::move(position);
        return ptr;
    }
References positions.
Referenced by Scene::loadFromFile().
dump()
void PositionManager::dump () inline override virtual
Pure virtual update function.
This function should be implemented by derived classes to update the state of their managed components each frame.
Pure virtual dump function for debugging.
This function should be implemented by derived classes to print the current state of all managed components to the console.
Implements IComponentManager.
Definition at line 30 of file PositionManager.h.
{
        std::cout << "PositionManager Dump:\n";
        if(
            positions.empty() ) {
            std::cout << "No positions available.\n";
            return;
        }
        std::cout << "Total positions: " << positions.size() << "\n";
        std::cout << "Positions:\n";
        std::cout << "-------------------\n";
        std::cout << "Entity UID | Position (x, y)\n";
        std::cout << "-------------------\n";
        for (const auto& pair : positions) {
            const PositionComponent* pos = pair.second.get();
            std::cout << "Entity UID: " << pair.first << " Position: (" << pos->x << ", " << pos->y << ")\n";
        }
    }
References positions, PositionComponent::x, and PositionComponent::y.
get()
PositionComponent * PositionManager::get (unsigned int entityUID) const inline
Definition at line 21 of file PositionManager.h.
{
        auto it = positions.find(entityUID);
        return (it != positions.end()) ? it->second.get() : nullptr;
    }
References positions.
Referenced by AISystem::executeMovementPlan(), PlayerController::handleEvent(), AISystem::planNextAction(), AISystem::processArrivingEntities(), AISystem::processPlanningEntities(), RenderableManager::renderAll(), InfoBoxManager::renderAll(), AISystem::updateAI(), and MovementManager::updateMovement().
Member Data Documentation
positions
std::unordered_map<unsigned int, std::unique_ptr<PositionComponent> > PositionManager::positions
Definition at line 12 of file PositionManager.h.
Referenced by create(), dump(), and get().
The documentation for this class was generated from the following file:
/home/sean/Projects/Brenda/src/ECS/PositionManager.h