Brenda: PlayerController Class Reference
PlayerController Class Reference
A controller that translates user keyboard input into entity movement.
#include <PlayerController.h>
Public Member Functions
PlayerController ()
void handleEvent (const SDL_Event &event, unsigned int uid, MovementManager &moveManager, PositionManager &posManager, const Grid &grid, int cellSize)
Handles SDL keyboard events to move the player entity.
Public Member Functions inherited from Controller
Controller (const std::string &t="unknown")
virtual void update ()
Public Member Functions inherited from ECS::IComponent
virtual ~IComponent ()=default
Additional Inherited Members
Public Attributes inherited from Controller
std::string type
Detailed Description
A controller that translates user keyboard input into entity movement.
Definition at line 15 of file PlayerController.h.
Constructor & Destructor Documentation
PlayerController()
PlayerController::PlayerController () inline
Definition at line 18 of file PlayerController.h.
: Controller("player") {}
Member Function Documentation
handleEvent()
void PlayerController::handleEvent (const SDL_Event & event, unsigned int uid, MovementManager & moveManager, PositionManager & posManager, const Grid & grid, int cellSize) inline
Handles SDL keyboard events to move the player entity.
Parameters
event The SDL_Event to process.
uid The UID of the entity this controller belongs to.
moveManager Reference to the MovementManager.
posManager Reference to the PositionManager.
grid The game grid, for collision checks.
cellSize The size of a grid cell in pixels.
Definition at line 29 of file PlayerController.h.
    {
        auto *movement = moveManager.get(uid);
        if (!movement || movement->isMoving)
        {
            return;
        }
        if (event.type == SDL_EVENT_KEY_DOWN)
        {
            auto *pos = posManager.get(uid);
            if (!pos) return;
            // Determine the entity's current grid cell from its pixel position
            int currentGridX = static_cast<int>(pos->x / cellSize);
            int currentGridY = static_cast<int>(pos->y / cellSize);
            // Determine the target grid cell based on keyboard input
            int targetGridX = currentGridX;
            int targetGridY = currentGridY;
            bool key_pressed = false;
            switch (event.key.scancode)
            {
            case SDL_SCANCODE_W: targetGridY--; key_pressed = true; break;
            case SDL_SCANCODE_S: targetGridY++; key_pressed = true; break;
            case SDL_SCANCODE_A: targetGridX--; key_pressed = true; break;
            case SDL_SCANCODE_D: targetGridX++; key_pressed = true; break;
            default: break;
            }
            if (key_pressed)
            {
                // Check if the target cell is within grid bounds and is walkable
                if (targetGridX >= 0 && targetGridX < grid.getWidth() &&
                    targetGridY >= 0 && targetGridY < grid.getHeight() &&
                    grid.at(targetGridX, targetGridY).obstacle == ObstacleType::None)
                {
                    // Calculate the pixel coordinates of the CENTER of the target cell
                    float targetPixelX = targetGridX * cellSize + (cellSize / 2.0f);
                    float targetPixelY = targetGridY * cellSize + (cellSize / 2.0f);
                    // Command the movement manager to move to the calculated center
                    movement->setTarget(targetPixelX, targetPixelY);
                    // CRITICAL FIX: Actually start the movement
                    movement->phase = MovementPhase::MOVING;
                    movement->phaseTimer = 0.0f;
                    movement->isMoving = true;
                    // Debug output
                    std::cout << "Player moving from (" << currentGridX << "," << currentGridY
                              << ") to (" << targetGridX << "," << targetGridY << ")" << std::endl;
                }
                else
                {
                    std::cout << "Cannot move to (" << targetGridX << "," << targetGridY
                              << ") - out of bounds or blocked" << std::endl;
                }
            }
        }
    }
References Grid::at(), MovementManager::get(), PositionManager::get(), Grid::getHeight(), Grid::getWidth(), MOVING, None, and Cell::obstacle.
The documentation for this class was generated from the following file:
/home/sean/Projects/Brenda/src/ECS/components/PlayerController.h