Brenda: TimeOfDay Class Reference
TimeOfDay Class Reference
#include <TimeOfDay.h>
Public Member Functions
TimeOfDay ()
void updateFromHour (int hour)
DayPeriod getCurrentPeriod () const
std::string getPeriodString () const
bool isDay () const
bool isNight () const
bool isWorkHours (int hour) const
bool isSleepTime (int hour) const
bool isMealTime (int hour) const
std::string getSuggestedActivity (int hour) const
bool isGoodTimeForWork (int hour) const
bool isGoodTimeForSleep (int hour) const
bool isGoodTimeForLeisure (int hour) const
Private Member Functions
DayPeriod calculatePeriod (int hour) const
Private Attributes
DayPeriod currentPeriod
Detailed Description
Definition at line 12 of file TimeOfDay.h.
Constructor & Destructor Documentation
TimeOfDay()
TimeOfDay::TimeOfDay ()
Definition at line 3 of file TimeOfDay.cpp.
                     : currentPeriod(DayPeriod::Morning) {
    // Default to morning
}
Member Function Documentation
calculatePeriod()
DayPeriod TimeOfDay::calculatePeriod (int hour) const private
Definition at line 11 of file TimeOfDay.cpp.
{
    if (hour >= 5 && hour < 8) return DayPeriod::Dawn;
    if (hour >= 8 && hour < 12) return DayPeriod::Morning;
    if (hour >= 12 && hour < 17) return DayPeriod::Afternoon;
    if (hour >= 17 && hour < 20) return DayPeriod::Evening;
    return DayPeriod::Night;
}
References Afternoon, Dawn, Evening, Morning, and Night.
Referenced by updateFromHour().
getCurrentPeriod()
DayPeriod TimeOfDay::getCurrentPeriod () const inline
Definition at line 20 of file TimeOfDay.h.
{ return currentPeriod; }
References currentPeriod.
getPeriodString()
std::string TimeOfDay::getPeriodString () const
Definition at line 19 of file TimeOfDay.cpp.
{
    switch (currentPeriod) {
        case DayPeriod::Dawn: return "Dawn";
        case DayPeriod::Morning: return "Morning";
        case DayPeriod::Afternoon: return "Afternoon";
        case DayPeriod::Evening: return "Evening";
        case DayPeriod::Night: return "Night";
    }
    return "Unknown";
}
References Afternoon, currentPeriod, Dawn, Evening, Morning, and Night.
Referenced by renderClock().
getSuggestedActivity()
std::string TimeOfDay::getSuggestedActivity (int hour) const
Definition at line 56 of file TimeOfDay.cpp.
{
    if (isSleepTime(hour)) return "Sleeping";
    if (isWorkHours(hour)) return "Working";
    if (isMealTime(hour)) return "Eating";
    switch (currentPeriod) {
        case DayPeriod::Dawn: return "Morning routine";
        case DayPeriod::Morning: return "Socializing";
        case DayPeriod::Afternoon: return "Activities";
        case DayPeriod::Evening: return "Relaxing";
        case DayPeriod::Night: return "Resting";
    }
    return "Idle";
}
References Afternoon, currentPeriod, Dawn, Evening, isMealTime(), isSleepTime(), isWorkHours(), Morning, and Night.
isDay()
bool TimeOfDay::isDay () const
Definition at line 30 of file TimeOfDay.cpp.
{
    return currentPeriod == DayPeriod::Dawn ||
           currentPeriod == DayPeriod::Morning ||
           currentPeriod == DayPeriod::Afternoon ||
           currentPeriod == DayPeriod::Evening;
}
References Afternoon, currentPeriod, Dawn, Evening, and Morning.
isGoodTimeForLeisure()
bool TimeOfDay::isGoodTimeForLeisure (int hour) const
Definition at line 79 of file TimeOfDay.cpp.
{
    return currentPeriod == DayPeriod::Evening ||
           currentPeriod == DayPeriod::Afternoon ||
           (!isWorkHours(hour) && !isSleepTime(hour));
}
References Afternoon, currentPeriod, Evening, isSleepTime(), and isWorkHours().
isGoodTimeForSleep()
bool TimeOfDay::isGoodTimeForSleep (int hour) const
Definition at line 75 of file TimeOfDay.cpp.
{
    return isSleepTime(hour);
}
References isSleepTime().
isGoodTimeForWork()
bool TimeOfDay::isGoodTimeForWork (int hour) const
Definition at line 71 of file TimeOfDay.cpp.
{
    return isWorkHours(hour);
}
References isWorkHours().
isMealTime()
bool TimeOfDay::isMealTime (int hour) const
Definition at line 49 of file TimeOfDay.cpp.
{
    // Breakfast: 7:00-9:00, Lunch: 12:00-13:00, Dinner: 18:00-20:00
    return (hour >= 7 && hour < 9) ||
           (hour >= 12 && hour < 13) ||
           (hour >= 18 && hour < 20);
}
Referenced by getSuggestedActivity().
isNight()
bool TimeOfDay::isNight () const
Definition at line 37 of file TimeOfDay.cpp.
{
    return currentPeriod == DayPeriod::Night;
}
References currentPeriod, and Night.
isSleepTime()
bool TimeOfDay::isSleepTime (int hour) const
Definition at line 45 of file TimeOfDay.cpp.
{
    return hour >= 22 || hour < 6;
}
Referenced by getSuggestedActivity(), isGoodTimeForLeisure(), and isGoodTimeForSleep().
isWorkHours()
bool TimeOfDay::isWorkHours (int hour) const
Definition at line 41 of file TimeOfDay.cpp.
{
    return hour >= 9 && hour < 17;
}
Referenced by getSuggestedActivity(), isGoodTimeForLeisure(), and isGoodTimeForWork().
updateFromHour()
void TimeOfDay::updateFromHour (int hour)
Definition at line 7 of file TimeOfDay.cpp.
{
    currentPeriod = calculatePeriod(hour);
}
References calculatePeriod(), and currentPeriod.
Referenced by Clock::Clock(), and Clock::updateTimeComponents().
Member Data Documentation
currentPeriod
DayPeriod TimeOfDay::currentPeriod private
Definition at line 37 of file TimeOfDay.h.
Referenced by getCurrentPeriod(), getPeriodString(), getSuggestedActivity(), isDay(), isGoodTimeForLeisure(), isNight(), and updateFromHour().
The documentation for this class was generated from the following files:
/home/sean/Projects/Brenda/src/TimeOfDay.h
/home/sean/Projects/Brenda/src/TimeOfDay.cpp