Brenda: Pathfinder Class Reference
Pathfinder Class Reference
#include <Pathfinder.h>
Public Member Functions
Pathfinder (const Grid &grid)
Constructs a Pathfinder that operates on a given grid.
std::vector< Point > findPath (Point start, Point end)
Finds the shortest path from a start point to an end point using A*.
std::vector< Point > findPathToZone (Point start, const std::string &zoneName)
Finds the shortest path from a start point to the nearest valid cell of a named zone.
Private Member Functions
std::vector< Point > reconstructPath (const std::vector< Point > &cameFrom, Point current)
int calculateHeuristic (Point a, Point b)
Private Attributes
const Grid & grid
Detailed Description
Definition at line 16 of file Pathfinder.h.
Constructor & Destructor Documentation
Pathfinder()
Pathfinder::Pathfinder (const Grid & grid) explicit
Constructs a Pathfinder that operates on a given grid.
Parameters
grid A constant reference to the grid to navigate.
Definition at line 22 of file Pathfinder.cpp.
: grid(grid) {}
Member Function Documentation
calculateHeuristic()
int Pathfinder::calculateHeuristic (Point a, Point b) private
Definition at line 24 of file Pathfinder.cpp.
{
    // Manhattan distance is a good heuristic for grid movement (no diagonals)
    return std::abs(a.x - b.x) + std::abs(a.y - b.y);
}
References Point::x, and Point::y.
Referenced by findPath().
findPath()
std::vector< Point > Pathfinder::findPath (Point start, Point end)
Finds the shortest path from a start point to an end point using A*.
Parameters
start The starting grid coordinates.
end The destination grid coordinates.
Returns
A vector of Points representing the path. Empty if no path is found.
Definition at line 43 of file Pathfinder.cpp.
{
    if (start == end || grid.at(end.x, end.y).obstacle == ObstacleType::Wall) {
        return {}; // No path needed or destination is a wall
    }
    std::priority_queue<Node, std::vector<Node>, std::greater<Node>> openSet;
    std::vector<Point> cameFrom(grid.getWidth() * grid.getHeight(), {-1, -1});
    std::vector<int> gCost(grid.getWidth() * grid.getHeight(), INT_MAX);
    gCost[start.y * grid.getWidth() + start.x] = 0;
    openSet.push({start, 0, calculateHeuristic(start, end)});
    int dx[] = {0, 0, 1, -1};
    int dy[] = {1, -1, 0, 0};
    while (!openSet.empty()) {
        Node current = openSet.top();
        openSet.pop();
        if (current.point == end) {
            return reconstructPath(cameFrom, current.point);
        }
        for (int i = 0; i < 4; ++i) {
            Point neighborPoint = {current.point.x + dx[i], current.point.y + dy[i]};
            if (neighborPoint.x < 0 || neighborPoint.x >= grid.getWidth() ||
                neighborPoint.y < 0 || neighborPoint.y >= grid.getHeight() ||
                grid.at(neighborPoint.x, neighborPoint.y).obstacle == ObstacleType::Wall) {
                continue;
            }
            int tentative_gCost = gCost[current.point.y * grid.getWidth() + current.point.x] + grid.at(neighborPoint.x, neighborPoint.y).cost;
            int neighborIndex = neighborPoint.y * grid.getWidth() + neighborPoint.x;
            if (tentative_gCost < gCost[neighborIndex]) {
                cameFrom[neighborIndex] = current.point;
                gCost[neighborIndex] = tentative_gCost;
                int hCost = calculateHeuristic(neighborPoint, end);
                openSet.push({neighborPoint, tentative_gCost, hCost});
            }
        }
    }
    return {}; // No path found
}
References Grid::at(), calculateHeuristic(), Cell::cost, Grid::getHeight(), Grid::getWidth(), grid, Cell::obstacle, Node::point, reconstructPath(), Wall, Point::x, and Point::y.
Referenced by findPathToZone().
findPathToZone()
std::vector< Point > Pathfinder::findPathToZone (Point start, const std::string & zoneName)
Finds the shortest path from a start point to the nearest valid cell of a named zone.
Parameters
start The starting grid coordinates.
zoneName The name of the destination zone (e.g., "Cafe", "Forest").
Returns
A vector of Points representing the path. Empty if no path or zone is found.
Definition at line 90 of file Pathfinder.cpp.
{
    auto it = grid.zones.find(zoneName);
    if (it == grid.zones.end()) {
        return {}; // Zone not found
    }
    const Zone& zone = it->second;
    std::vector<Point> bestPath;
    // Iterate over all cells in the zone to find the shortest path to any of them
    for (int y = zone.y; y < zone.y + zone.height; ++y) {
        for (int x = zone.x; x < zone.x + zone.width; ++x) {
            if (grid.at(x, y).obstacle != ObstacleType::Wall) {
                std::vector<Point> currentPath = findPath(start, {x, y});
                if (!currentPath.empty() && (bestPath.empty() || currentPath.size() < bestPath.size())) {
                    bestPath = currentPath;
                }
            }
        }
    }
    return bestPath;
}
References Grid::at(), findPath(), grid, Zone::height, Cell::obstacle, Wall, Zone::width, Zone::x, Zone::y, and Grid::zones.
Referenced by AISystem::executeMovementPlan().
reconstructPath()
std::vector< Point > Pathfinder::reconstructPath (const std::vector< Point > & cameFrom, Point current) private
Definition at line 29 of file Pathfinder.cpp.
{
    std::vector<Point> total_path;
    total_path.push_back(current);
    int currentIndex = current.y * grid.getWidth() + current.x;
    while (cameFrom[currentIndex].x != -1) { // -1 indicates no parent
        current = cameFrom[currentIndex];
        total_path.push_back(current);
        currentIndex = current.y * grid.getWidth() + current.x;
    }
    std::reverse(total_path.begin(), total_path.end());
    return total_path;
}
References Grid::getWidth(), grid, Point::x, and Point::y.
Referenced by findPath().
Member Data Documentation
grid
const Grid& Pathfinder::grid private
Definition at line 41 of file Pathfinder.h.
Referenced by findPath(), findPathToZone(), and reconstructPath().
The documentation for this class was generated from the following files:
/home/sean/Projects/Brenda/src/Pathfinder.h
/home/sean/Projects/Brenda/src/Pathfinder.cpp