Brenda: DescriptionComponentManager Class Reference
DescriptionComponentManager Class Reference
#include <DescriptionComponentManager.h>
Public Member Functions
DescriptionComponent * create (unsigned int entityUID, const std::string &name, const std::string &text)
DescriptionComponent * get (unsigned int entityUID)
void dump ()
Pure virtual update function.
virtual void update ()
Public Member Functions inherited from IComponentManager
virtual ~IComponentManager ()=default
Virtual destructor.
Public Attributes
std::unordered_map< unsigned int, std::unique_ptr< DescriptionComponent > > descriptions
Detailed Description
Definition at line 9 of file DescriptionComponentManager.h.
Member Function Documentation
create()
DescriptionComponent * DescriptionComponentManager::create (unsigned int entityUID, const std::string & name, const std::string & text) inline
Definition at line 13 of file DescriptionComponentManager.h.
{
        auto desc = std::make_unique<DescriptionComponent>(name, text);
        DescriptionComponent* ptr = desc.get();
        descriptions[entityUID] = std::move(desc);
        return ptr;
    }
References descriptions.
Referenced by Scene::loadFromFile().
dump()
void DescriptionComponentManager::dump () inline virtual
Pure virtual update function.
This function should be implemented by derived classes to update the state of their managed components each frame.
Pure virtual dump function for debugging.
This function should be implemented by derived classes to print the current state of all managed components to the console.
Implements IComponentManager.
Definition at line 25 of file DescriptionComponentManager.h.
                {
        std::cout << "--- Description Components ---" << std::endl;
        for (const auto& pair : descriptions) {
            std::cout << "Entity " << pair.first << ": " << pair.second->name << " - " << pair.second->text << std::endl;
        }
    }
References descriptions.
Referenced by main(), and update().
get()
DescriptionComponent * DescriptionComponentManager::get (unsigned int entityUID) inline
Definition at line 20 of file DescriptionComponentManager.h.
{
        auto it = descriptions.find(entityUID);
        return (it != descriptions.end()) ? it->second.get() : nullptr;
    }
References descriptions.
Referenced by AISystem::planNextAction(), AISystem::processArrivingEntities(), AISystem::processPlanningEntities(), and AISystem::updateAI().
update()
virtual void DescriptionComponentManager::update () inline virtual
Definition at line 32 of file DescriptionComponentManager.h.
{
        // for now lets call dump() to show descriptions
        dump();
    };
References dump().
Member Data Documentation
descriptions
std::unordered_map<unsigned int, std::unique_ptr<DescriptionComponent> > DescriptionComponentManager::descriptions
Definition at line 11 of file DescriptionComponentManager.h.
Referenced by create(), dump(), and get().
The documentation for this class was generated from the following file:
/home/sean/Projects/Brenda/src/ECS/DescriptionComponentManager.h