Brenda: Clock Class Reference
Clock Class Reference
#include <Clock.h>
Public Member Functions
Clock (float timeScale=60.0f)
void update (float deltaTime)
int getHour () const
int getMinute () const
int getDay () const
float getTotalSeconds () const
const TimeOfDay & getTimeOfDay () const
TimeOfDay & getTimeOfDay ()
std::string getTimeString () const
void setTimeScale (float scale)
float getTimeScale () const
void pause ()
void resume ()
bool isPaused () const
Private Member Functions
void updateTimeComponents ()
Private Attributes
float totalSeconds
int hour
int minute
int day
TimeOfDay timeOfDay
float timeScale
bool paused
Detailed Description
Definition at line 5 of file Clock.h.
Constructor & Destructor Documentation
Clock()
Clock::Clock (float timeScale = 60.0f)
Definition at line 5 of file Clock.cpp.
    : totalSeconds(0.0f)
    , hour(8)  // Start at 8 AM
    , minute(0)
    , day(1)
    , timeOfDay()
    , timeScale(timeScale)
    , paused(false)
{
    // Initialize time of day with starting hour
    timeOfDay.updateFromHour(hour);
}
References hour, timeOfDay, and TimeOfDay::updateFromHour().
Member Function Documentation
getDay()
int Clock::getDay () const inline
Definition at line 14 of file Clock.h.
{ return day; }
References day.
getHour()
int Clock::getHour () const inline
Definition at line 12 of file Clock.h.
{ return hour; }
References hour.
Referenced by AISystem::planNextAction(), AISystem::processArrivingEntities(), AISystem::processPlanningEntities(), and AISystem::shouldReplanActivity().
getMinute()
int Clock::getMinute () const inline
Definition at line 13 of file Clock.h.
{ return minute; }
References minute.
getTimeOfDay() [1/2]
TimeOfDay & Clock::getTimeOfDay () inline
Definition at line 19 of file Clock.h.
{ return timeOfDay; }
References timeOfDay.
getTimeOfDay() [2/2]
const TimeOfDay & Clock::getTimeOfDay () const inline
Definition at line 18 of file Clock.h.
{ return timeOfDay; }
References timeOfDay.
Referenced by AISystem::planNextAction(), AISystem::processArrivingEntities(), AISystem::processPlanningEntities(), renderClock(), and AISystem::shouldReplanActivity().
getTimeScale()
float Clock::getTimeScale () const inline
Definition at line 26 of file Clock.h.
{ return timeScale; }
References timeScale.
Referenced by main().
getTimeString()
std::string Clock::getTimeString () const
Definition at line 43 of file Clock.cpp.
{
    std::stringstream ss;
    ss << "Day " << day << " - "
       << std::setfill('0') << std::setw(2) << hour << ":"
       << std::setfill('0') << std::setw(2) << minute;
    return ss.str();
}
References day, hour, and minute.
Referenced by renderClock().
getTotalSeconds()
float Clock::getTotalSeconds () const inline
Definition at line 15 of file Clock.h.
{ return totalSeconds; }
References totalSeconds.
isPaused()
bool Clock::isPaused () const inline
Definition at line 29 of file Clock.h.
{ return paused; }
References paused.
pause()
void Clock::pause () inline
Definition at line 27 of file Clock.h.
{ paused = true; }
References paused.
Referenced by main().
resume()
void Clock::resume () inline
Definition at line 28 of file Clock.h.
{ paused = false; }
References paused.
Referenced by main().
setTimeScale()
void Clock::setTimeScale (float scale) inline
Definition at line 25 of file Clock.h.
{ timeScale = scale; }
References timeScale.
Referenced by main().
update()
void Clock::update (float deltaTime)
Definition at line 18 of file Clock.cpp.
{
    if (paused) return;
    totalSeconds += deltaTime * timeScale;
    updateTimeComponents();
}
References paused, timeScale, totalSeconds, and updateTimeComponents().
Referenced by main().
updateTimeComponents()
void Clock::updateTimeComponents () private
Definition at line 25 of file Clock.cpp.
{
    // Convert total seconds to hours, minutes, and days
    int totalMinutes = static_cast<int>(totalSeconds / 60.0f);
    int totalHours = totalMinutes / 60;
    // minute = totalMinutes % 60;
    // hour = (8 + totalHours) % 24;  // Start at 8 AM
    // day = 1 + (8 + totalHours) / 24;  // Day advances every 24 hours
    minute = totalMinutes % 60;
    hour = (totalHours) % 24;  // Start at 8 AM
    day = 1 + (totalHours) / 24;  // Day advances every 24 hours
    // Update time of day based on current hour
    timeOfDay.updateFromHour(hour);
}
References day, hour, minute, timeOfDay, totalSeconds, and TimeOfDay::updateFromHour().
Referenced by update().
Member Data Documentation
day
int Clock::day private
Definition at line 35 of file Clock.h.
Referenced by getDay(), getTimeString(), and updateTimeComponents().
hour
int Clock::hour private
Definition at line 33 of file Clock.h.
Referenced by Clock(), getHour(), getTimeString(), and updateTimeComponents().
minute
int Clock::minute private
Definition at line 34 of file Clock.h.
Referenced by getMinute(), getTimeString(), and updateTimeComponents().
paused
bool Clock::paused private
Definition at line 40 of file Clock.h.
Referenced by isPaused(), pause(), resume(), and update().
timeOfDay
TimeOfDay Clock::timeOfDay private
Definition at line 37 of file Clock.h.
Referenced by Clock(), getTimeOfDay(), getTimeOfDay(), and updateTimeComponents().
timeScale
float Clock::timeScale private
Definition at line 39 of file Clock.h.
Referenced by getTimeScale(), setTimeScale(), and update().
totalSeconds
float Clock::totalSeconds private
Definition at line 32 of file Clock.h.
Referenced by getTotalSeconds(), update(), and updateTimeComponents().
The documentation for this class was generated from the following files:
/home/sean/Projects/Brenda/src/Clock.h
/home/sean/Projects/Brenda/src/Clock.cpp