Brenda: MovementManager Class Reference
MovementManager Class Reference
#include <MovementManager.h>
Public Member Functions
Movement * create (unsigned int entityUID, float speed)
Movement * get (unsigned int entityUID)
void update (PositionManager &posManager, float deltaTime, float timeScale=1.0f)
std::vector< unsigned int > getEntitiesInPhase (MovementPhase phase)
Gets all entities in a specific movement phase.
bool canEntityMove (unsigned int entityUID)
Checks if an entity can accept new movement commands.
void dump () override
Pure virtual update function.
Public Member Functions inherited from IComponentManager
virtual ~IComponentManager ()=default
Virtual destructor.
Public Attributes
std::unordered_map< unsigned int, std::unique_ptr< Movement > > movements
Private Member Functions
void updateMovement (unsigned int uid, Movement *movement, PositionManager &posManager, float deltaTime, float timeScale=1.0f)
Detailed Description
Definition at line 10 of file MovementManager.h.
Member Function Documentation
canEntityMove()
bool MovementManager::canEntityMove (unsigned int entityUID) inline
Checks if an entity can accept new movement commands.
Definition at line 102 of file MovementManager.h.
{
        auto* movement = get(entityUID);
        return movement ? movement->canAcceptNewTarget() : true;
    }
References get().
create()
Movement * MovementManager::create (unsigned int entityUID, float speed) inline
Definition at line 14 of file MovementManager.h.
{
        auto move = std::make_unique<Movement>(speed);
        Movement* ptr = move.get();
        movements[entityUID] = std::move(move);
        return ptr;
    }
References movements.
Referenced by Scene::loadFromFile().
dump()
void MovementManager::dump () inline override virtual
Pure virtual update function.
This function should be implemented by derived classes to update the state of their managed components each frame.
Pure virtual dump function for debugging.
This function should be implemented by derived classes to print the current state of all managed components to the console.
Implements IComponentManager.
Definition at line 107 of file MovementManager.h.
{}
get()
Movement * MovementManager::get (unsigned int entityUID) inline
Definition at line 21 of file MovementManager.h.
{
        auto it = movements.find(entityUID);
        return (it != movements.end()) ? it->second.get() : nullptr;
    }
References movements.
Referenced by canEntityMove(), AISystem::executeMovementPlan(), PlayerController::handleEvent(), main(), AISystem::planNextAction(), AISystem::processArrivingEntities(), AISystem::processPlanningEntities(), and AISystem::updateAI().
getEntitiesInPhase()
std::vector< unsigned int > MovementManager::getEntitiesInPhase (MovementPhase phase) inline
Gets all entities in a specific movement phase.
Definition at line 89 of file MovementManager.h.
{
        std::vector<unsigned int> entities;
        for (const auto& [uid, movement] : movements) {
            if (movement->phase == phase) {
                entities.push_back(uid);
            }
        }
        return entities;
    }
References movements.
update()
void MovementManager::update (PositionManager & posManager, float deltaTime, float timeScale = 1.0f) inline
Definition at line 26 of file MovementManager.h.
{
        for (auto& [uid, movement] : movements) {
            // Update phase timer (scales with time)
            movement->phaseTimer += deltaTime * timeScale;
            // Handle phase transitions
            switch (movement->phase) {
                case MovementPhase::PLANNING:
                    if (movement->phaseTimer >= movement->planningDuration) {
                        movement->phase = MovementPhase::IDLE;
                        movement->phaseTimer = 0.0f;
                    }
                    break;
                case MovementPhase::ARRIVING:
                    if (movement->phaseTimer >= movement->arrivingDuration) {
                        movement->phase = MovementPhase::IDLE;
                        movement->phaseTimer = 0.0f;
                    }
                    break;
                case MovementPhase::MOVING:
                    updateMovement(uid, movement.get(), posManager, deltaTime, timeScale);
                    break;
                case MovementPhase::IDLE:
                    // Entity is idle, no movement updates needed
                    break;
            }
        }
    }
References ARRIVING, IDLE, movements, MOVING, PLANNING, and updateMovement().
Referenced by main().
updateMovement()
void MovementManager::updateMovement (unsigned int uid, Movement * movement, PositionManager & posManager, float deltaTime, float timeScale = 1.0f) inline private
Definition at line 59 of file MovementManager.h.
{
        auto* pos = posManager.get(uid);
        if (!pos) return;
        float dx = movement->targetX - pos->x;
        float dy = movement->targetY - pos->y;
        float distance = std::sqrt(dx * dx + dy * dy);
        // Calculate how far we should move in this single frame (scaled by time)
        float moveDistance = movement->speed * deltaTime * timeScale;
        // If the remaining distance is less than this frame's movement,
        // snap to the target and transition to arriving phase.
        if (distance <= moveDistance) {
            pos->x = movement->targetX;
            pos->y = movement->targetY;
            movement->isMoving = false;
            movement->phase = MovementPhase::ARRIVING;
            movement->phaseTimer = 0.0f;
        } else {
            // Otherwise, move towards the target by the calculated distance
            pos->x += (dx / distance) * moveDistance;
            pos->y += (dy / distance) * moveDistance;
        }
    }
References ARRIVING, PositionManager::get(), Movement::isMoving, Movement::phase, Movement::phaseTimer, Movement::speed, Movement::targetX, and Movement::targetY.
Referenced by update().
Member Data Documentation
movements
std::unordered_map<unsigned int, std::unique_ptr<Movement> > MovementManager::movements
Definition at line 12 of file MovementManager.h.
Referenced by create(), get(), getEntitiesInPhase(), and update().
The documentation for this class was generated from the following file:
/home/sean/Projects/Brenda/src/ECS/MovementManager.h