Brenda: RenderableManager Class Reference
RenderableManager Class Reference
#include <RenderableManager.h>
Public Member Functions
Square * createQuad (unsigned int entityUID, float x, float y, SDL_Color color)
Circle * createCircle (unsigned int entityUID, float x, float y, SDL_Color color)
void renderAll (SDL_Renderer *ren, PositionManager &positionManager) const
void dump () override
Pure virtual update function.
Public Member Functions inherited from IComponentManager
virtual ~IComponentManager ()=default
Virtual destructor.
Public Attributes
std::unordered_map< unsigned int, std::unique_ptr< IRenderable > > renderables
Detailed Description
Definition at line 13 of file RenderableManager.h.
Member Function Documentation
createCircle()
Circle * RenderableManager::createCircle (unsigned int entityUID, float x, float y, SDL_Color color) inline
Definition at line 27 of file RenderableManager.h.
{
        auto circle = std::make_unique<Circle>(x, y, 16, color);
        Circle* ptr = circle.get();
        renderables[entityUID] = std::move(circle);
        return ptr;
    }
References renderables.
Referenced by Scene::loadFromFile().
createQuad()
Square * RenderableManager::createQuad (unsigned int entityUID, float x, float y, SDL_Color color) inline
Definition at line 19 of file RenderableManager.h.
{
        auto square = std::make_unique<Square>(x, y, 32, color);
        Square* ptr = square.get();
        renderables[entityUID] = std::move(square);
        return ptr;
    }
References renderables.
dump()
void RenderableManager::dump () inline override virtual
Pure virtual update function.
This function should be implemented by derived classes to update the state of their managed components each frame.
Pure virtual dump function for debugging.
This function should be implemented by derived classes to print the current state of all managed components to the console.
Implements IComponentManager.
Definition at line 47 of file RenderableManager.h.
{
        std::cout << "RenderableManager Dump:\n";
        for (const auto& pair : renderables) {
            const IRenderable* renderable = pair.second.get();
            if (renderable) {
                std::cout << "Entity UID: " << pair.first
                          << " Renderable Rect: ("
                          << renderable->rect.x << ", "
                          << renderable->rect.y << ", "
                          << renderable->rect.w << ", "
                          << renderable->rect.h << ")\n";
            }
        }
    }
References IRenderable::rect, and renderables.
renderAll()
void RenderableManager::renderAll (SDL_Renderer * ren, PositionManager & positionManager) const inline
Definition at line 34 of file RenderableManager.h.
{
        for (const auto& [uid, r] : renderables) {
            if (r) {
                auto pos = positionManager.get(uid);
                if (pos) {
                    r->rect.x = pos->x - (r->rect.w / 2);
                    r->rect.y = pos->y - (r->rect.h / 2);
                }
                r->render(ren);
            }
        }
    }
References PositionManager::get(), renderables, and PositionComponent::x.
Referenced by main().
Member Data Documentation
renderables
std::unordered_map<unsigned int, std::unique_ptr<IRenderable> > RenderableManager::renderables
Definition at line 16 of file RenderableManager.h.
Referenced by createCircle(), createQuad(), dump(), and renderAll().
The documentation for this class was generated from the following file:
/home/sean/Projects/Brenda/src/ECS/RenderableManager.h