Brenda: TiledParser Class Reference
TiledParser Class Reference
Parser for Tiled Map Editor JSON files.
#include <TiledParser.h>
Classes
struct TiledLayer
struct TiledObjectGroup
struct TiledTileset
Static Public Member Functions
static bool loadTiledMap (const std::string &filename, Grid &grid)
Load a Tiled JSON file and populate the given Grid.
Static Private Member Functions
static void processTileLayer (const nlohmann::json &layer, Grid &grid, const std::vector< TiledTileset > &tilesets)
static void processObjectGroup (const nlohmann::json &layer, Grid &grid)
static ObstacleType stringToObstacleType (const std::string &typeStr)
static int getDefaultCost (ObstacleType obstacle)
Detailed Description
Parser for Tiled Map Editor JSON files.
Supports loading tile maps created with Tiled (https://www.mapeditor.org/) and converting them to our Grid format.
Definition at line 16 of file TiledParser.h.
Member Function Documentation
getDefaultCost()
static int TiledParser::getDefaultCost (ObstacleType obstacle) inline static private
Definition at line 256 of file TiledParser.h.
{
        switch (obstacle) {
            case ObstacleType::Wall: return 9999;
            case ObstacleType::Water: return 50;
            case ObstacleType::Forest: return 10;
            case ObstacleType::Grass: return 1;
            case ObstacleType::Path: return 0;
            default: return 1;
        }
    }
References Forest, Grass, Path, Wall, and Water.
Referenced by processTileLayer().
loadTiledMap()
static bool TiledParser::loadTiledMap (const std::string & filename, Grid & grid) inline static
Load a Tiled JSON file and populate the given Grid.
Parameters
filename Path to the Tiled JSON file
grid Grid object to populate
Returns
true if successful, false otherwise
Definition at line 53 of file TiledParser.h.
{
        std::ifstream file(filename);
        if (!file) {
            std::cerr << "Failed to open Tiled file: " << filename << std::endl;
            return false;
        }
        nlohmann::json j;
        try {
            j = nlohmann::json::parse(file);
        } catch (const nlohmann::json::parse_error& e) {
            std::cerr << "Error parsing Tiled JSON: " << e.what() << std::endl;
            return false;
        }
        // Validate this is a Tiled map
        if (!j.contains("type") || j["type"] != "map") {
            std::cerr << "Not a valid Tiled map file" << std::endl;
            return false;
        }
        // Get map dimensions
        int mapWidth = j.value("width", 0);
        int mapHeight = j.value("height", 0);
        int tileWidth = j.value("tilewidth", 32);
        int tileHeight = j.value("tileheight", 32);
        std::cout << "Loading Tiled map: " << mapWidth << "x" << mapHeight
                  << " (tile size: " << tileWidth << "x" << tileHeight << ")" << std::endl;
        // Resize grid to match map
        grid = Grid(mapWidth, mapHeight);
        // Load tilesets
        std::vector<TiledTileset> tilesets;
        if (j.contains("tilesets")) {
            for (const auto& tilesetRef : j["tilesets"]) {
                TiledTileset tileset;
                tileset.firstgid = tilesetRef.value("firstgid", 1);
                // Handle embedded vs external tilesets
                if (tilesetRef.contains("source")) {
                    // External tileset - would need to load from separate file
                    std::cerr << "External tilesets not yet supported" << std::endl;
                    continue;
                } else {
                    // Embedded tileset
                    tileset.name = tilesetRef.value("name", "");
                    tileset.tilewidth = tilesetRef.value("tilewidth", tileWidth);
                    tileset.tileheight = tilesetRef.value("tileheight", tileHeight);
                    tileset.tilecount = tilesetRef.value("tilecount", 0);
                    tileset.columns = tilesetRef.value("columns", 1);
                    tileset.image = tilesetRef.value("image", "");
                }
                // Load tile properties and types
                if (tilesetRef.contains("tiles")) {
                    for (const auto& tileData : tilesetRef["tiles"]) {
                        int tileId = tileData.value("id", 0);
                        int globalId = tileset.firstgid + tileId;
                        if (tileData.contains("type")) {
                            tileset.tileTypes[globalId] = tileData["type"];
                        }
                        if (tileData.contains("properties")) {
                            for (const auto& prop : tileData["properties"]) {
                                if (prop.contains("name") && prop["name"] == "cost") {
                                    tileset.tileCosts[globalId] = prop.value("value", 1);
                                }
                            }
                        }
                    }
                }
                tilesets.push_back(tileset);
                std::cout << "Loaded tileset: " << tileset.name << " (firstgid=" << tileset.firstgid << ")" << std::endl;
            }
        }
        // Load layers
        if (j.contains("layers")) {
            for (const auto& layerJson : j["layers"]) {
                std::string layerType = layerJson.value("type", "");
                std::string layerName = layerJson.value("name", "");
                bool visible = layerJson.value("visible", true);
                if (!visible) continue; // Skip invisible layers
                if (layerType == "tilelayer") {
                    // Tile layer - contains the actual tile data
                    processTileLayer(layerJson, grid, tilesets);
                } else if (layerType == "objectgroup") {
                    // Object layer - contains zones, spawn points, etc.
                    processObjectGroup(layerJson, grid);
                }
            }
        }
        return true;
    }
References TiledParser::TiledTileset::columns, TiledParser::TiledTileset::firstgid, TiledParser::TiledTileset::image, TiledParser::TiledTileset::name, processObjectGroup(), processTileLayer(), TiledParser::TiledTileset::tileCosts, TiledParser::TiledTileset::tilecount, TiledParser::TiledTileset::tileheight, TiledParser::TiledTileset::tileTypes, and TiledParser::TiledTileset::tilewidth.
Referenced by Grid::loadFromTiled().
processObjectGroup()
static void TiledParser::processObjectGroup (const nlohmann::json & layer, Grid & grid) inline static private
Definition at line 206 of file TiledParser.h.
{
        std::string layerName = layer.value("name", "");
        std::cout << "Processing object group: " << layerName << std::endl;
        if (layer.contains("objects")) {
            for (const auto& obj : layer["objects"]) {
                std::string name = obj.value("name", "");
                std::string type = obj.value("type", "");
                float x = obj.value("x", 0.0f);
                float y = obj.value("y", 0.0f);
                float width = obj.value("width", 0.0f);
                float height = obj.value("height", 0.0f);
                // Convert pixel coordinates to tile coordinates
                // (assuming 32x32 tiles, but could be made configurable)
                int tileX = static_cast<int>(x / 32);
                int tileY = static_cast<int>(y / 32);
                int tileWidth = static_cast<int>(width / 32);
                int tileHeight = static_cast<int>(height / 32);
                // Add zone to grid
                if (!name.empty() && tileWidth > 0 && tileHeight > 0) {
                    grid.zones[name] = {tileX, tileY, tileWidth, tileHeight};
                    std::cout << "Added zone: " << name << " (" << tileX << "," << tileY
                              << " " << tileWidth << "x" << tileHeight << ")" << std::endl;
                }
            }
        }
    }
References Grid::zones.
Referenced by loadTiledMap().
processTileLayer()
static void TiledParser::processTileLayer (const nlohmann::json & layer, Grid & grid, const std::vector< TiledTileset > & tilesets) inline static private
Definition at line 156 of file TiledParser.h.
{
        std::string layerName = layer.value("name", "");
        int layerWidth = layer.value("width", 0);
        int layerHeight = layer.value("height", 0);
        std::cout << "Processing tile layer: " << layerName << std::endl;
        if (layer.contains("data")) {
            std::vector<int> tileData = layer["data"];
            for (int y = 0; y < layerHeight && y < grid.getHeight(); ++y) {
                for (int x = 0; x < layerWidth && x < grid.getWidth(); ++x) {
                    int index = y * layerWidth + x;
                    if (index >= tileData.size()) continue;
                    int gid = tileData[index];
                    if (gid == 0) continue; // Empty tile
                    // Find which tileset this tile belongs to
                    const TiledTileset* tileset = nullptr;
                    for (auto it = tilesets.rbegin(); it != tilesets.rend(); ++it) {
                        if (gid >= it->firstgid) {
                            tileset = &(*it);
                            break;
                        }
                    }
                    if (!tileset) continue;
                    // Set tile properties
                    Cell& cell = grid.at(x, y);
                    // Set obstacle type based on tile type
                    if (tileset->tileTypes.count(gid)) {
                        std::string tileType = tileset->tileTypes.at(gid);
                        cell.obstacle = stringToObstacleType(tileType);
                    }
                    // Set movement cost
                    if (tileset->tileCosts.count(gid)) {
                        cell.cost = tileset->tileCosts.at(gid);
                    } else {
                        // Default costs based on obstacle type
                        cell.cost = getDefaultCost(cell.obstacle);
                    }
                }
            }
        }
    }
References Grid::at(), Cell::cost, getDefaultCost(), Grid::getHeight(), Grid::getWidth(), Cell::obstacle, stringToObstacleType(), TiledParser::TiledTileset::tileCosts, and TiledParser::TiledTileset::tileTypes.
Referenced by loadTiledMap().
stringToObstacleType()
static ObstacleType TiledParser::stringToObstacleType (const std::string & typeStr) inline static private
Definition at line 236 of file TiledParser.h.
{
        static std::unordered_map<std::string, ObstacleType> mapping = {
            {"Wall", ObstacleType::Wall},
            {"wall", ObstacleType::Wall},
            {"Water", ObstacleType::Water},
            {"water", ObstacleType::Water},
            {"Forest", ObstacleType::Forest},
            {"forest", ObstacleType::Forest},
            {"Grass", ObstacleType::Grass},
            {"grass", ObstacleType::Grass},
            {"Path", ObstacleType::Path},
            {"path", ObstacleType::Path},
            {"None", ObstacleType::None},
            {"none", ObstacleType::None}
        };
        auto it = mapping.find(typeStr);
        return (it != mapping.end()) ? it->second : ObstacleType::None;
    }
References Forest, Grass, None, Path, Wall, and Water.
Referenced by processTileLayer().
The documentation for this class was generated from the following file:
/home/sean/Projects/Brenda/src/TiledParser.h